# Example ESPHome configuration for Gree AC Modbus RTU (ESP8266/ESP-01)
# Copy this file and modify for your setup

substitutions:
  device_name: gree-ac
  friendly_name: "Gree AC"
  slave_id: "1"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Disable serial logging since GPIO1/GPIO3 are used for Modbus
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External component from GitHub
external_components:
  - source: github://sgtaziz/esphome_gree_modbus
    components: [gree_ac]

# UART for RS485 communication (uses hardware serial pins)
# Note: Disconnect RS485 module when flashing
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# Gree AC Climate component
climate:
  - platform: gree_ac
    name: ${friendly_name}
    id: gree_ac_unit
    slave_id: ${slave_id}
    update_interval: 5s

    # Optional sensors and controls
    outdoor_temperature:
      name: "${friendly_name} Outdoor Temperature"

    # Note: ESP-01 has limited RAM, you may need to disable some
    # optional features if you encounter memory issues
    vertical_swing_select:
      name: "${friendly_name} Vertical Swing"

    horizontal_swing_select:
      name: "${friendly_name} Horizontal Swing"

    sleep_switch:
      name: "${friendly_name} Sleep Mode"

    turbo_switch:
      name: "${friendly_name} Turbo Mode"

    fresh_air_switch:
      name: "${friendly_name} Fresh Air"
