# Example ESPHome configuration for Gree AC Modbus RTU
# Copy this file and modify for your setup

substitutions:
  device_name: gree-ac
  friendly_name: "Gree AC"
  slave_id: "1"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# External component from GitHub
external_components:
  - source: github://sgtaziz/esphome_gree_modbus
    components: [gree_ac]

# UART for RS485 communication
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# Gree AC Climate component
climate:
  - platform: gree_ac
    name: ${friendly_name}
    id: gree_ac_unit
    slave_id: ${slave_id}
    update_interval: 5s

    # Flow control pin for MAX485 modules (directly controls DE/RE pins)
    # Not needed for auto-direction RS485 modules - remove or comment out
    flow_control_pin: GPIO4

    # Optional sensors and controls
    outdoor_temperature:
      name: "${friendly_name} Outdoor Temperature"

    vertical_swing_select:
      name: "${friendly_name} Vertical Swing"

    horizontal_swing_select:
      name: "${friendly_name} Horizontal Swing"

    sleep_switch:
      name: "${friendly_name} Sleep Mode"

    turbo_switch:
      name: "${friendly_name} Turbo Mode"

    fresh_air_switch:
      name: "${friendly_name} Fresh Air"

# Diagnostic sensors
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"
    unit_of_measurement: "h"
    filters:
      - lambda: return x / 3600.0;

# Diagnostic buttons
button:
  - platform: restart
    name: "${friendly_name} Restart"

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"

# Diagnostic text sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"

  - platform: version
    name: "${friendly_name} ESPHome Version"
